# Uncomment the next line to define a global platform for your project

platform :ios, '15.0'

target 'Myguni' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Myguni
    pod 'SnapKit'
    pod 'Then'
    pod 'RealmSwift'
    pod 'TextFieldEffects'

end
